#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%% Brunilda Balliu 
#%%%%%%%%%%%%%%% April 21st 2020
#%%%%%%%%%%%%%%% Script to run TreeQTL by content
#%%%%%%%%%%%%%%% For Hoffman
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# qrsh -l h_data=80G,h_rt=12:00:00,highp
# module load R/3.6.1

## Arguments and parameters
args=commandArgs(TRUE)
exp_scale=as.numeric(args[1])

# FDR thresholds
level1=0.01
level2=0.01
level3=0.01

## Libraries 
library(MatrixEQTL)
library(TreeQTL)
library(dplyr)

# use a single thread
print(paste0("data.table getDTthreads(): ",getDTthreads()))
setDTthreads(1)
print(paste0("after setting as 1 thread; data.table getDTthreads(): ",getDTthreads()))

# Display all warnings as they occur
options(warn=1)

## Location of data files.
project.dir = '/u/project/zaitlenlab/bballiu/FastGxE';
source(file = paste0(project.dir,'/scripts/00_functions.R'))

## Assign TISSUE_NAME and scale
if(exp_scale == 1) exp_suffix = ".v8.EUR.normalized_expression"
if(exp_scale == 2) exp_suffix = ".v8.EUR.normalized_and_residualized_expression"
if(exp_scale == 3) exp_suffix = ".v8.EUR.normalized_expression_heterogeneous"
if(exp_scale == 4) exp_suffix = ".v8.EUR.normalized_and_residualized_expression_heterogeneous"
if(exp_scale == 5) exp_suffix = ".v8.EUR.normalized_expression_homogeneous"
if(exp_scale == 6) exp_suffix = ".v8.EUR.normalized_and_residualized_expression_homogeneous"

#### Perform hierarchical selection for eGenes across multiple tissues by first selecting eGenes which are subject to genetic regulation in any tissue, then the tissues in which they are regulated, and finally the specific SNPs associated to each selected gene x tissue pair

#m_eqtl_out_dir: path to output files with eQTL output per tissue. 
# These are assumed to follow the output format generated by Matrix eQTL.
m_eqtl_out_dir=paste0(project.dir, "/results/eQTL_mapping/MatrixEQTL_FDRthreshold");
# m_eqtl_out_dir=paste0(project.dir, "/results/eQTL_mapping/MatrixEQTL");
treeQTL_dir=paste0(project.dir, "/results/eQTL_mapping/TreeQTL");

#tissue_names: vector of names for each tissue in alphanumeric order
pattern=paste0(exp_suffix,".all_pairs.txt")
tissue_names=sort(gsub(pattern = paste(exp_suffix,".all_pairs.txt",sep = "|"), replacement = "", x = list.files(m_eqtl_out_dir, pattern = pattern, full.names = FALSE)))

# Get eGenes. 
if(exp_scale %in% 1:4){
  
  if(length(tissue_names)!=49) stop(sprintf("Expecting 49 tissues but got %i.", length(tissue_names)))
  
  eGenes = get_eGenes_multi_tissue_mod(m_eqtl_out_dir = m_eqtl_out_dir, 
                                       treeQTL_dir=treeQTL_dir, 
                                       tissue_names=tissue_names, 
                                       level1 = level1, level2 = level1, level3 = level1, 
                                       exp_suffix=exp_suffix)
  fwrite(x = eGenes,file = paste0(treeQTL_dir,"/eGenes",exp_suffix,".txt"), sep = '\t', row.names = F, col.names = T)
  
  
}

if(exp_scale %in% 5:6){
  
  m_eqtl_outfile <- list.files(m_eqtl_out_dir, pattern = pattern, full.names = TRUE)
  n_SNPs_per_gene_outfile <- list.files(treeQTL_dir, pattern = "n_SNPs_per_gene_AverageTissue.txt", full.names = TRUE)
  
  n_tests_per_gene <- data.frame(fread(input = n_SNPs_per_gene_outfile, header = F), stringsAsFactors = F,check.names = F)
  colnames(n_tests_per_gene)=c("family","n_tests")
  n_tests_per_gene <- n_tests_per_gene[n_tests_per_gene$n_tests > 0, ]
  
  eGenes=get_eGenes(n_tests_per_gene = n_tests_per_gene, m_eqtl_out=m_eqtl_outfile, method = "BY", level1 = level1, level2 = level2) 
  fwrite(x = eGenes,file = paste0(treeQTL_dir,"/eGenes",exp_suffix,".txt"), sep = '\t', row.names = F, col.names = T)
  
  get_eAssociations(eDiscoveries=eGenes, n_tests =n_tests_per_gene, m_eqtl_out = m_eqtl_outfile, 
                    out_file = paste0(treeQTL_dir,"/eAssoc_by_gene.AverageTissue",exp_suffix,".txt"), by_snp = FALSE)
}

# Get eSNPs
if(0){
if(exp_scale %in% 1:4){
  
  snps_by_tissue_file=paste0(project.dir, "/data/GTEx_v8/misc/GTEx_v8_SNPs_by_Tissue.txt")
  if(file.exists(snps_by_tissue_file)){
    print("Reading snps-by-tissue file")
    snps_by_tissue=fread(input = snps_by_tissue_file, header = T, sep = ',')  
  } else {
    print("Making snps-by-tissue file")
    MAF=data.frame(fread(input = paste0(project.dir,"/data/GTEx_v8/misc/GTEx_v8_SNPs_by_Tissue_MAF.txt"), header = T))
    snps_by_tissue = MAF
    for(i in 2:ncol(snps_by_tissue)){
      snps_by_tissue[,i] = (rowSums(MAF[,-1]>=0.05)>=2)&(MAF[,i]>=0.05)
    }
    fwrite(x = snps_by_tissue, file = paste0(project.dir, "/data/GTEx_v8/misc/GTEx_v8_SNPs_by_Tissue.txt"), col.names = T, row.names = F)
  }
  
  genes_by_tissue = data.frame(fread(input = "/u/project/zaitlenlab/bballiu/FastGxE/data/GTEx_v8/misc/GTEx_v8_Gene_by_Tissue_Expression.txt", header = T), 
                               check.names = F,stringsAsFactors = F)
  genes_by_tissue[rowSums(genes_by_tissue[,-1])<2,-1]=0
  
  n_tests_per_SNP=data.frame(fread(input = paste0(project.dir, "/results/eQTL_mapping/TreeQTL/n_genes_per_SNPs_Heterogeneous.txt"),
                                   header = F),check.names = F, stringsAsFactors = F)
  colnames(n_tests_per_SNP)=c("family", "n_tests")

  eSNPs = get_eSNPs_multi_tissue_mod(genes_by_tissue = genes_by_tissue, snps_by_tissue = snps_by_tissue, 
                                     n_tests_per_SNP = n_tests_per_SNP, m_eqtl_out_dir = m_eqtl_out_dir, 
                                     tissue_names=tissue_names, level1 = level1, level2 = level2, level3 = level3, 
                                     exp_suffix=exp_suffix)   
  
  fwrite(x = eSNPs,file = paste0(treeQTL_dir,"/eSNPs",exp_suffix,".txt"), sep = '\t', row.names = F, col.names = T)
  
}

if(exp_scale %in% 5:6){
  
  n_tests_per_SNP=data.frame(fread(input = paste0(project.dir, "/results/eQTL_mapping/TreeQTL/n_genes_per_SNPs_Homogeneous.txt"),
                                   header = F),check.names = F, stringsAsFactors = F)
  colnames(n_tests_per_SNP)=c("family", "n_tests")
  
  m_eqtl_out <- list.files(m_eqtl_out_dir, pattern = pattern, full.names = TRUE)
  
  eSNPs = get_eSNPs(n_tests_per_SNP = n_tests_per_SNP, m_eqtl_out = m_eqtl_out, level1 = level1, level2 = level2)
  fwrite(x = eSNPs,file = paste0(treeQTL_dir,"/eSNPs",exp_suffix,".txt"), sep = '\t', row.names = F, col.names = T)
  
}
}


print("run_TreeQTL.R finished!")